CREATE TABLE job_applications
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company VARCHAR(100) NOT NULL,
    position VARCHAR(100) NOT NULL,
    status VARCHAR(255) NOT NULL,
    application_date DATE NOT NULL
);